import Mathlib.Tactic

/-!
# Generated Spectral Numeric Rows

Generated by `tools/generate_spectral_eigs.py` from `data/li_n_intervals.csv`.
Do not edit by hand; regenerate in CI.
-/

namespace RhCore.Spectral.GeneratedEigs

structure GeneratedRow where
  n : Nat
  mid : ℝ
  rad : ℝ

def rows : List GeneratedRow := [
  { n := 10, mid := ((7171472409516259 : ℚ) / 2500000000000000 : ℚ), rad := ((1 : ℚ) / 1000000000000 : ℚ) },
  { n := 11, mid := ((7805469288332911 : ℚ) / 2500000000000000 : ℚ), rad := ((1 : ℚ) / 1000000000000 : ℚ) },
  { n := 12, mid := ((1683647914993237 : ℚ) / 500000000000000 : ℚ), rad := ((1 : ℚ) / 1000000000000 : ℚ) }
]

def lowerEndpoint (row : GeneratedRow) : ℝ :=
  row.mid - row.rad

theorem lowerEndpoint_eq (row : GeneratedRow) :
    lowerEndpoint row = row.mid - row.rad := by
  rfl

/-- Exact lower endpoint positivity for generated row n=10. -/
theorem lowerPositive_10 : (0 : ℝ) < ((7171472409516259 : ℚ) / 2500000000000000 : ℚ) - ((1 : ℚ) / 1000000000000 : ℚ) := by
  norm_num

/-- Exact lower endpoint positivity for generated row n=11. -/
theorem lowerPositive_11 : (0 : ℝ) < ((7805469288332911 : ℚ) / 2500000000000000 : ℚ) - ((1 : ℚ) / 1000000000000 : ℚ) := by
  norm_num

/-- Exact lower endpoint positivity for generated row n=12. -/
theorem lowerPositive_12 : (0 : ℝ) < ((1683647914993237 : ℚ) / 500000000000000 : ℚ) - ((1 : ℚ) / 1000000000000 : ℚ) := by
  norm_num


end RhCore.Spectral.GeneratedEigs
