#!/usr/bin/env python3
"""Generate a small Lean module from certified numeric interval rows.

Input is a CSV with at least:
  n, midpoint/radius  or  n, mid/rad

Output is a Lean module containing exact rational midpoint/radius rows and
positivity witnesses for rows whose lower endpoint is positive. This is a
lightweight current-repo substitute for a future `auto_convert.py` that will
consume richer FLINT/Arb reports.
"""

from __future__ import annotations

import argparse
import csv
from decimal import Decimal
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, help="numeric interval CSV")
    parser.add_argument("--out", required=True, help="Lean output path")
    return parser.parse_args()


def to_q(value: str) -> str:
    numerator, denominator = Decimal(value).as_integer_ratio()
    return f"(({numerator} : ℚ) / {denominator} : ℚ)"


def main() -> int:
    args = parse_args()
    input_path = Path(args.input)
    out_path = Path(args.out)

    with input_path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)
        fields = reader.fieldnames or []

    mid_col = "midpoint" if "midpoint" in fields else "mid"
    rad_col = "radius" if "radius" in fields else "rad"
    if "n" not in fields or mid_col not in fields or rad_col not in fields:
        raise ValueError(f"expected n plus midpoint/radius or mid/rad columns, got {fields}")
    if not rows:
        raise ValueError("input CSV has no rows")

    lean_rows: list[str] = []
    lemmas: list[str] = []
    for row in rows:
        n = int(row["n"])
        mid = to_q(row[mid_col])
        rad = to_q(row[rad_col])
        lean_rows.append(f"  {{ n := {n}, mid := {mid}, rad := {rad} }}")
        if Decimal(row[mid_col]) - Decimal(row[rad_col]) > 0:
            lemmas.append(
                f"/-- Exact lower endpoint positivity for generated row n={n}. -/\n"
                f"theorem lowerPositive_{n} : (0 : ℝ) < {mid} - {rad} := by\n"
                f"  norm_num\n\n"
            )

    content = f"""import Mathlib.Tactic

/-!
# Generated Spectral Numeric Rows

Generated by `tools/generate_spectral_eigs.py` from `{input_path.as_posix()}`.
Do not edit by hand; regenerate in CI.
-/

namespace RhCore.Spectral.GeneratedEigs

structure GeneratedRow where
  n : Nat
  mid : ℝ
  rad : ℝ

def rows : List GeneratedRow := [
{",\n".join(lean_rows)}
]

def lowerEndpoint (row : GeneratedRow) : ℝ :=
  row.mid - row.rad

theorem lowerEndpoint_eq (row : GeneratedRow) :
    lowerEndpoint row = row.mid - row.rad := by
  rfl

{"".join(lemmas)}
end RhCore.Spectral.GeneratedEigs
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

